### ISSUE TITLE
[ Feat ] 메인 페이지 추가

### ISSUE THREAD

**Issue by sinji2102** [TEAM-BEAT/BEAT-Client#104]
### 🛠 Issue

예매 페이지 추가 

### 📝 To-do

- [x] 예매 페이지 추가
- [x] 공연 목록 구현
- [x] 칩 구현
- [x] footer 구현
- [ ] navigate bar 구현
- [ ] 햄버거 -> 사이드바 구현

### 🔍 접근 방법

carousel 제외하고 메인 view / 페이지만 우선 작업하고 carousel 작업할 때 issue 새로 파겠습니다!

들어가야 하는 컴포넌트 (크게)
- carousel
- performance
- chip
- footer
