### ISSUE TITLE
[ Feat ] 예매자 삭제 기능 추가 (ticketholderlist 페이지)

### ISSUE THREAD

**Issue by ocahs9** [TEAM-BEAT/BEAT-Client#111]
### 🛠 Issue

원래 새롭게 예매자 삭제 페이지를 만들까 하다가, 예메자 리스트 페이지의 기능을 거의 그대로 사용해야 하는 이유로,
기존 ticketholderlist 페이지에 기능만 추가하기로 결정했습니다.

### 📝 To-do

- [x] 기존 예매자 리스트 페이지에서 삭제 버튼을 클릭할 시, Navigation 헤더와 페이지 뷰가 조금 변하도록 구현 (State로 구현 예정)
- [x] 체크박스 누르면 각 ManagerCard에 해당하는 오브젝트를 인식하도록 만들기 (onClick으로 상위 컴포넌트의 state가 변하도록)
- [x] 하단의 '삭제' 버튼을 클릭하면 Delete API 요청 보내기, 그리고 실제로 삭제하기 - 그리고 다시 요청 받아오는 구조 짜놓기
- [x] 체크된 오브젝트들 배열로 만들어서 한번에 요청으로 만들어서 보내기

### 🔍 접근 방법

어차피 요청 보내는 걸로 만들어야 하니까 지금 상수 데이터를 변경시키는 것은 고려하지 않았습니다. 
즉, 현재 api가 연결되어 있지 않은 상태에서는 아무리 삭제 요청을 보내도 실제로 삭제되는 모습을 볼 수는 없습니다.
feat/#66/NarrowDropDown 브랜치의 하위 브랜치로 파서 작업한 뒤, develop 으로 머지해두도록 하겠습니다.
