### ISSUE TITLE
[ Feat ] URL 네이밍, 버튼에 적절한 기능들 연결

### ISSUE THREAD

**Issue by ocahs9** [TEAM-BEAT/BEAT-Client#126]
### 🛠 Issue

페이지 컴포넌트의 라우팅 주소를 결정된 URL로 전부 수정하겠습니다.
페이지 흐름대로 연결해두겠습니다. (채현이 뷰, 도영이 뷰 연결해두기)
모든 버튼에 적절한 onClick 연결해두기. 

### 📝 To-do

- [x] 모든 페이지 유기적으로 연결하기 
- [x] 페이지 컴포넌트들에 해당하는 URL들 정확히 설정해두기
- [x] 모든 버튼들에 onClick 적절하게 연결해두기

### 🔍 접근 방법

이 이슈 다음엔 API를 위한 구조들을 세팅하겠습니다.
