### ISSUE TITLE
[ Fix ] 비회원 예매 조회 - 회원 예매 조회 페이지 내 오류 수정

### ISSUE THREAD

**Issue by sinji2102** [TEAM-BEAT/BEAT-Client#142]
### 🛠 Issue

비회원 예매 조회 - 회원 예매 조회 화면에 있는 오류나 미처 반영하지 못한 디자인들 잡겠습니다~

### 📝 To-do

회원 예매 조회
- [ ]  회원 예매 조회 카드에 right arrow 추가
- [ ]  회원 예매 조회 이미지에 라벨 추가 + 관람종료 라벨
---
비회원 예매 조회
- [ ]  비회원 예매 조회란 input 입력 검사 수정

### 🔍 접근 방법

.
