### ISSUE TITLE
[ Feat ] 상세 및 예매 페이지 연결 및 자잘한 오류 수정

### ISSUE THREAD

**Issue by pepperdad** [TEAM-BEAT/BEAT-Client#146]
### 🛠 Issue

상세 및 예매 페이지를 연결하고, 자잘한 오류 수정

### 📝 To-do

- [x] 완료 페이지로 navigate (state 전달 포함)
- [x] genre에 따라 view 변경
- [x] 로그인 관련 바텀시트 추가
- [x] 카카오 로그인 연결
- [x] 출연진 없을 떄 보여줄 컴포넌트 추가 
- [ ] 시간 형식 서버랑 논의하기
- [x] ShowType 각 공연 타입에 따라 다른 뷰 리턴
- [x] 헤더 뷰 및 네비게이션

### 🔍 접근 방법

.
