### ISSUE TITLE
[ Fix ] 예매자 리스트 뷰 수정

### ISSUE THREAD

**Issue by ocahs9** [TEAM-BEAT/BEAT-Client#160]
### 🛠 Issue

To - do 확인 하기!

### 📝 To-do

- [x] gap 2.4rem -> 1.2rem 으로 수정
- [x] 체크박스 컬러 확인
- [x] 토글 텍스트 항상 '자세히'

### 🔍 접근 방법

수정합니다 !
