### ISSUE TITLE
[ Bug ] 메인 페이지 자잘한 오류 수정

### ISSUE THREAD

**Issue by sinji2102** [TEAM-BEAT/BEAT-Client#161]
### 🐛 Issue

#104
#120 
#122 

### 🐝 버그 발생 부분

1. 햄버거바 스크롤 및 옆으로 튀어나감
2. 페이지 이동했다 돌아오면 페이지바 닫기
3. 배너 위치
4. 플로팅 사이드바 열어도 위에 뜸

### 📝 To-do

- [ ]  메인 햄버거바 위치 수정하기 (현재 옆으로 튀어나감)
- [ ]  메인 햄버거바 배경 아예 선택 못하게 하기 (현재 스크롤 됨)
- [ ]  메인 공연 등록 배너 전체 공연 볼 때만 띄우기
- [ ]  메인 페이지 이동했다 돌아오면 햄버거바 닫혀 있게 하기
- [ ] 플로팅 버튼 사이드바 열리면 가리기
