### ISSUE TITLE
[ Bug ] 예매 조회 페이지 변경사항 반영

### ISSUE THREAD

**Issue by sinji2102** [TEAM-BEAT/BEAT-Client#178]
### 🐛 Issue

[ Feat ] 예매 조회 페이지 추가 #72

### 🐝 버그 발생 부분

1. 회원 예매 조회 계좌 확인 모달 변경
2.  회원 예매 조회 계좌 버튼 디자인 변경
3. 회원 예매 관람 회차와 총 금액 추가 등 카드 변경
4. 회원 예매 공연 종료되면 계좌 보기 삭제

### 📝 To-do

- [ ]  회원 예매 조회 계좌 확인 모달 변경 사항 반영
- [ ]  회원 예매 조회 계좌 버튼 디자인 변경 사항 반영
- [ ]  회원 예매 관람 회차와 총 금액 추가 등 카드 변경 사항 반영
- [ ]  회원 예매 공연 종료되면 계좌 보기 삭제
