### ISSUE TITLE
[ Feat ] 티켓 API - 입금 여부 정보 수정 API 연결

### ISSUE THREAD

**Issue by ocahs9** [TEAM-BEAT/BEAT-Client#188]
### 🛠 Issue

.

### 📝 To-do

- [ ] 입금 여부 정보 수정 API 연결
- [ ] 예매자 삭제 API 연결
- [ ] 웹발신 API 연결

### 🔍 접근 방법

.
