### ISSUE TITLE
[ Feat ] 예매 관련 공연 정보 조회 API, 티켓 예매 가능 여부 조회 API, 비회원 예매 요청 API 추가

### ISSUE THREAD

**Issue by pepperdad** [TEAM-BEAT/BEAT-Client#192]
### 🛠 Issue

gig 페이지에 사용되는 예매 관련 공연 정보 조회 API 연결

### 📝 To-do

- [x] 예매 관련 공연 정보 조회 API
- [x] 티켓 예매 가능 여부 조회 API
- [x] 비회원 예매 요청 API 추가

### 🔍 접근 방법

.
