### ISSUE TITLE
[ Feat ] 유저 API 소셜로그인 회원가입/로그인

### ISSUE THREAD

**Issue by sinji2102** [TEAM-BEAT/BEAT-Client#195]
### 🛠 Issue

유저 API 소셜로그인 회원가입/로그인에 필요한 API 연결 기능입니다 

### 📝 To-do

- [x] POST API 쿼리 작성
- [x] POST API 작성
- [x] 로그인 리다이렉트 페이지에서 POST 되도록 작성

### 🔍 접근 방법

현재 토큰 발급 안 되어서 코드만 우선 작성하겠습니다 키키
