### ISSUE TITLE
[ Bug ] 디자인 QA 사항 일부 반영

### ISSUE THREAD

**Issue by sinji2102** [TEAM-BEAT/BEAT-Client#208]
### 🐛 Issue

전반적인 오류 수정이라 이슈 번호 적지 않겠습니다~

### 🐝 버그 발생 부분

- 예매 조회 페이지 계좌 닫기 버튼 색상 다름
- 플로팅 버튼 위치 날라다님
- 취소하기 바텀 시트 누르면 사라짐
- 취소하기 바텀 시트 복사 시 토스트 메시지 노출 안 됨

### 📝 To-do

- [ ]  예매 조회 계좌 닫기 버튼 pink -> gray
- [ ]  플로팅 버튼 위치 수정
- [x]  취소하기 -> 확인했어요 눌러야 바텀시트 이벤트 버블링 막기
- [x]  취소하기 바텀 시트 복사 시 토스트 메시지 뜨도록
