### ISSUE TITLE
[ Feat ] 예매하기 관련 공연 정보 조회 API

### ISSUE THREAD

**Issue by ocahs9** [TEAM-BEAT/BEAT-Client#210]
### 🛠 Issue

.

### 📝 To-do

- [ ] 공연 상세정보 조회 API
- [ ] 예매하기 관련 공연 정보 조회 API
- [ ] 공연 삭제 API (이거 스웨거에 안 올라옴)
- [ ]  ticketholderlist 에 params 넘겨주는 거 구현

### 🔍 접근 방법

.
