### ISSUE TITLE
[ Feat ] 예매 완료 페이지 + 공연 상세 페이지 QA 반

### ISSUE THREAD

**Issue by ocahs9** [TEAM-BEAT/BEAT-Client#264]
### 🛠 Issue

.

### 📝 To-do

- [ ] 예매 완료 페이지 얼라인 중앙으로 맞춰주기
- [ ] 공연 상세페이지 하단에 문의하기 전화번호 → 복사는 되는데 토스트가 안뜸
- [ ] 공연 상세페이지 뷰에서 ‘문의 연락처’ 언더라인 제거

### 🔍 접근 방법

.
