### ISSUE TITLE
[ Bug ] 예매 완료 페이지 + 공연 상세 페이지 QA 반영

### ISSUE THREAD

**Issue by ocahs9** [TEAM-BEAT/BEAT-Client#265]
### 🐛 Issue

QA반영

### 🐝 버그 발생 부분

QA반영

### 📝 To-do

- [ ] 예매 완료 페이지 얼라인 중앙으로 맞춰주기
- [ ] 공연 상세페이지 하단에 문의하기 전화번호 → 복사는 되는데 토스트가 안뜸
- [ ] 공연 상세페이지 뷰에서 ‘문의 연락처’ 언더라인 제거
