### ISSUE TITLE
[ Feat ] 로그아웃 기능 구현

### ISSUE THREAD

**Issue by sinji2102** [TEAM-BEAT/BEAT-Client#322]
### 🛠 Issue

햄버거 사이드바  내 로그아웃 기능 구현. 현재 로그아웃을 할 수 없어 로그아웃 기능을 구현하고자 합니다

### 📝 To-do

- [x] 햄버거 사이드바에 로그아웃 추가
- [x]  로그아웃 API 연결
- [x] localStorage에 있는 토큰 제거

### 🔍 접근 방법

로그아웃 API 연결 및 로컬스토리지 내 토큰 제거하는 로직 추가하겠습니다~

**Comment by sinji2102** [comment]
스프린트 기능이었다니... 1차 스프린트에 시작하게습니당
