### ISSUE TITLE
[ Refactor ] 공연 수정하기 코드 전부 리팩토링

### ISSUE THREAD

**Issue by ocahs9** [TEAM-BEAT/BEAT-Client#340]
### ♻️ Issue

'공연 등록하기'의 코드의 흐름을 참고하되, 
'공연 수정하기'의 유지 보수의 용이성을 위해 리팩토링 하도록 하겠습니다.

### 🔢 리팩토링하는 이슈를 기입해주세요.

#147

### 📣 리팩토링 목적

1. 직접 작성한 코드가 아니라서 코드 자체에 대한 이해도가 떨어짐
2. 유지 보수의 불편함
3. 적절한 주석 첨가

### 📝 To-do

- [x] API 요청으로 받아오는 데이터에 맞게 코드 작성
- [ ] 데이트 피커, 타임 피커, DayJs 라이브러리 폐기  -> 캘린더의 여러가지 기능 직접 구현
- [x] 언제든지 디자인 변경이 가능하도록, 로직과 뷰 분리
- [ ] 바깥 클릭 시 해당 요소가 사라지는 유틸 함수 구현 (useOutsideClick)
- [x] 코드 가독성 향상을 위한 정리
