### ISSUE TITLE
[ !HOTFIX ] 캐러셀 이동할 url 수정 및 1개 들어갔을 때 고정

### ISSUE THREAD

**Issue by sinji2102** [TEAM-BEAT/BEAT-Client#349]
### 🐛 Issue

[ Feat ] 캐러셀 슬라이드 기능 추가 #338

### 🐝 버그 발생 부분

1. 현재 캐러셀 url을 외부로 이동할 수 없음
2. 1개만 들어갔을 때 제대로 굴러가지 않음
3. 이미지 비율 타 브랜치에서 수정했으나 아직 merge 안 함

### 📝 To-do

- [x] 캐러셀 외부로 이동할 수 있도록 url 수정
- [x] 1개만 들어갔을 때 고정될 수 있도록 수정
- [x] 이미지 비율 수정 (다른 이슈에서 해결했으나 아직 merge를 안 함)
