### ISSUE TITLE
[ Feat ] Bottom Sheet 공통 컴포넌트 추가

### ISSUE THREAD

**Issue by sinji2102** [TEAM-BEAT/BEAT-Client#35]
### 🛠 Issue

![image](https://github.com/TEAM-BEAT/BEAT-Client/assets/66528589/7b842661-ffe5-472a-ac55-fda783829eb4)

### 📝 To-do

- [ ] View 바텀 시트 생성
- [ ] Action 바텀 시트 생성
- [ ] check 바텀 시트 생성
- [ ] bank 바텀 시트 생성

### 🔍 접근 방법

view 바텀 시트의 경우 날짜에 중간선이 하나 필요해 date라는 type을 하나 더 생성할 예정입니다.
