### ISSUE TITLE
[ Refactor ] 메인 및 예매 확인 페이지 1차 스프린트 디자인 반영

### ISSUE THREAD

**Issue by sinji2102** [TEAM-BEAT/BEAT-Client#362]
### ♻️ Issue

포스터 비율 변경 및 1차 스프린트 기간에 변경된 전반적인 디자인 변경사항 반영하겠습니다~

### 🔢 리팩토링하는 이슈를 기입해주세요.

#114 ... 등등 전반적으로 변경된 사항들 반영하겠습니다

### 📣 리팩토링 목적

1. 포스터 이미지 3:4 변경과 함께 전반적인 디자인 변경
2. 디자인 측면.... 에서 변경된 듯

### 📝 To-do

- [x] main 화면 글자 패딩값 변경
- [x] poster 컴포넌트 사이즈 변경
- [x] 예매내역 조회 뷰 전반적인 사이즈 및 패딩값 변경
