### ISSUE TITLE
[ Feat ] 예매자(게스트) 관리하기 리뉴얼

### ISSUE THREAD

**Issue by ocahs9** [TEAM-BEAT/BEAT-Client#380]
### 🛠 Issue

예매자 관리하기 페이지가 리뉴얼 되었습니다.

### 📝 To-do

- [ ] CSV 추출 기능 만들기
- [ ] 예매자 삭제, 입금 처리하기 기능 로직 변경
- [ ] 디자인 리뉴얼 및 자세히 보기 토글 삭제 
- [ ] 게스트 삭제, 입금 처리 모달 추가

### 🔍 접근 방법

기존의 데이터를 최대한 활용하여 변경할 예정입니다.
