### ISSUE TITLE
[ Bug ] '공연 수정하기' 에서 cast 미리보기 안 뜨는 문제 + 추가된 회차에 예매한 경우 csv에 반영 안되는 문제

### ISSUE THREAD

**Issue by ocahs9** [TEAM-BEAT/BEAT-Client#433]
### 🐛 Issue

.

### 🐝 버그 발생 부분

1. 아예 cast, staff 전부 없는 공연에서 순차적으로 cast를 추가하려고 하면 cast만 미리보기에서 안 뜨는 문제 발생
2. 추가된 회차를 예매한 경우 예매 내역엔 안 뜨는 문제

### 📝 To-do

- [x] cast 미리보기에 뜨도록 바꾸기 (수정 반영은 되고 있는 상태)
- [x] 추가된 회차 예매한 경우도 csv에 반영되도록 구현하기 
- [x] 공연이름 예매자 목록(다운시간)으로 csv이름 으로 csv 파일 명 변경하기
