### ISSUE TITLE
[ Refactor ] Button 컴포넌트 변경사항 반영

### ISSUE THREAD

**Issue by pepperdad** [TEAM-BEAT/BEAT-Client#444]
### 🛠 Issue

1. Design System이 변경됨에 따라, Button 컴포넌트의 disabled 상태를 전부 grey_disabled로 변경합니다.
  1.2 disabled 상태 Button의 폰트 컬러를 변경합니다. grey600->grey500
2. Design QA를 반영합니다.

### 📝 To-do

- [x] Button 컴포넌트의 disabled 상태를 전부 grey_disabled로 변경
- [x] disabled 상태 Button의 폰트 컬러를 변경 (grey600->grey500)
- [x] 공연 상세 이미지에 라운드 추가
- [x] 미리 보기 컴포넌트 - 등록된 ‘출연진’ 정보가 없어요 로 변경, z-index 수정 
- [ ] 헤더 텍스트 중앙 정렬 

### 🔍 접근 방법

.
