### ISSUE TITLE
[ Feat ] 예매자 관리 페이지 기능 구현

### ISSUE THREAD

**Issue by sinji2102** [TEAM-BEAT/BEAT-Client#453]
### 🛠 Issue

예매자 관리 페이지에 필요한 기능들 구현하겠습니다 하단 투두 참고!!

### 📝 To-do

- [x] 예매자 조회 GET API 연결
- [x] 예매자 조회 필터링 기능 추가
- [x] 예매자 조회 검색 기능 추가
- [x] 입금 처리 API 연결
- [x] 환불 처리 API 연결
- [x] 예매자 삭제 API 연결
- [x] CSV 다시 연결

### 🔍 접근 방법

.
