### ISSUE TITLE
[ Feat ] 공연 정보 수정사항 반영

### ISSUE THREAD

**Issue by imddoy** [TEAM-BEAT/BEAT-Client#455]
### 🛠 Issue

스프린트 때 변경된 부분들 반영

### 📝 To-do

- [x] 공연진 사진 선택사항
- [x] 공연소개, 유의사항 1500자 연장
- [x] 공연장소 글자수 제한 삭제

### 🔍 접근 방법

좀좀따리 변경해요
