### ISSUE TITLE
[ Feat ] QA 반영 

### ISSUE THREAD

**Issue by ocahs9** [TEAM-BEAT/BEAT-Client#470]
### 🛠 Issue

QA를 반영하도록 하겠습니다. 

### 📝 To-do

- [x] 공연장 주소 복사 토스트 위치 조정
- [x] 화살표 버튼이 CTA(목표 달성 버튼)보다 위에 오는 현상 수정 (z-index)
- [x] 주소 검색 모달의 검정색 스토로크 제거
- [x] 상세 공연 페이지 복사 완료 토스트 구현
- [x] 예매자 목록 다운로드 및 입금 & 환불 & 취소 처리 성공 토스트 구현 (피그마 참고)

### 🔍 접근 방법

.
