### ISSUE TITLE
[ Feat ] ticketholderlist 페이지 + NarrowDropDown 구현

### ISSUE THREAD

**Issue by ocahs9** [TEAM-BEAT/BEAT-Client#66]
### 🛠 Issue
![image](https://github.com/TEAM-BEAT/BEAT-Client/assets/155794105/f2aa6c75-1df4-464f-9509-0d9e371a20e0)

![image](https://github.com/TEAM-BEAT/BEAT-Client/assets/155794105/7ea5810d-3629-4008-94a4-83ef98d41f65)
이거 만들게요! 누르면 드롭다운 되는건데, 회차의 개수에 따라 드롭되는 내용이 달라질 수 있도록 구현하겠습니다.

### 📝 To-do
- [x] TicketHolderList  (공연에 따른 예매자 리스트) 페이지 제작
- [x] 드롭다운 뷰 구현
- [x] 모든 회차 드롭 다운의 경우, 
- [x] 드롭 다운을 누를 시 필터링이 되는 로직 구현
- [x] API 요청 고려해서 만들기 !

### 🔍 접근 방법

필터링이 좀 많이 섞여 있어서 공통 컴포넌트보다는 개인 컴포넌트로 제작하기로 마음 먹었고,
페이지에 종속적인 드롭 다운을 구현하기로 결정했습니다.
챌린징 좋다!
