### ISSUE TITLE
[ Feat ] 비회원 예매 조회 페이지 추가

### ISSUE THREAD

**Issue by sinji2102** [TEAM-BEAT/BEAT-Client#69]
### 🛠 Issue

![image](https://github.com/TEAM-BEAT/BEAT-Client/assets/66528589/703f6755-adff-4114-9a5a-7d6939e1477d)

비회원 예매 조회(Lookup) 페이지 추가
: navigation, input, button 포함

### 📝 To-do

- [ ] 비회원 예매 조회 페이지 네이밍
- [ ] Navigation 뒤로가기 버튼 누르면 메인으로 이동
- [ ] input에 입력한 내용 받을 수 있도록
- [ ] 네 개의 input을 모두 입력해야 버튼 활성화
- [ ] API 연결 전이므로 버튼 클릭하면 Lookup 페이지로 이동

### 🔍 접근 방법

[버튼 활성화 관련 velog](https://velog.io/@hyunjoong/react-button-%ED%99%9C%EC%84%B1%ED%99%94)
위 아티클 참고해서 개발할 예정입니다
