### ISSUE TITLE
[ Feat ] 예매 조회 페이지 추가

### ISSUE THREAD

**Issue by sinji2102** [TEAM-BEAT/BEAT-Client#72]
### 🛠 Issue

|기본|계좌번호 복사 팝업|취소 요청 바텀시트|
|------|---|---|
|![image](https://github.com/TEAM-BEAT/BEAT-Client/assets/66528589/4fed858c-df81-4562-a9ed-501eb14c2607)|![image](https://github.com/TEAM-BEAT/BEAT-Client/assets/66528589/f2d8eca0-06c3-4e42-ac40-d5c090d3f995)|![image](https://github.com/TEAM-BEAT/BEAT-Client/assets/66528589/860a9782-4f09-485c-9306-0c1a670a88a1)|

### 📝 To-do

- [x] API GET 고려해서 작성
- [x] 빈 배열일 시 빈 화면 분기
- [x] 예매 공연 card 컴포넌트
- [x] 계좌번호 버튼 선택 시 계좌번호 복사 팝업 생성
- [x] 취소 버튼 선택 시 대표자 연락처 바텀시트 생성

### 🔍 접근 방법
[navigate로 컴포넌트 이동시 props 전달 방법](https://9x211x2.tistory.com/22)
위 아티클 참고해서 navigate 사용!! 

토큰으로 분기 처리 ? GET으로 로그인 회원의 정보 받아오기 : navigation에서 온 props로 받기

.
